default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: Cmpt276ProjDev #myproj_development
  username: sfuplannerdev #postgres
  password: sfuplanner #121
  host: localhost


test:
  <<: *default
  database: Cmpt276ProjTest #myproj_development
  username: sfuplannertest #postgres
  password: sfuplanner #121
  host: localhost

production:
  <<: *default
  database: sfuPlanner_production
  username: sfuPlanner
password: <%= ENV['SFUPLANNER_DATABASE_PASSWORD'] %>
